env = rlPredefinedEnv('CartPole-Continuous');
obsInfo = getObservationInfo(env);
actInfo = getActionInfo(env);

agentOpts = rlSACAgentOptions;
agentOpts.SampleTime = 0.02;

agentOpts.ActorOptimizerOptions.LearnRate = 1e-4;
agentOpts.CriticOptimizerOptions(1).LearnRate = 1e-3;
agentOpts.CriticOptimizerOptions(2).LearnRate = 1e-3;

agentOpts.TargetSmoothFactor = 0.005;
agentOpts.ExperienceBufferLength = 1e6;
agentOpts.MiniBatchSize = 128;

agent = rlSACAgent(obsInfo, actInfo, agentOpts);

trainOpts = rlTrainingOptions(...
    'MaxEpisodes', 1000, ...
    'MaxStepsPerEpisode', 500, ...
    'StopTrainingCriteria', 'AverageReward', ...
    'StopTrainingValue', 490, ...
    'ScoreAveragingWindowLength', 20, ... 
    'SaveAgentCriteria', 'EpisodeReward', ...
    'SaveAgentValue', 500, ...
    'SaveAgentDirectory', pwd, ...
    'UseParallel', false, ...
    'Plots', 'training-progress');

trainingStats = train(agent, env, trainOpts);