
disp('Initializing Training Protocol...');

trainOpts = rlTrainingOptions(...
    'MaxEpisodes', 5000, ...               
    'MaxStepsPerEpisode', 500, ...         
    'ScoreAveragingWindowLength', 50, ...  
    'Verbose', false, ...
    'Plots', 'training-progress', ...      
    'StopTrainingCriteria', 'AverageReward', ...
    'StopTrainingValue', 800, ...          
    'SaveAgentCriteria', 'EpisodeReward', ...
    'SaveAgentValue', 200, ...             
    'SaveAgentDirectory', pwd);            

disp('Unleashing SAC Agent into the Environment...');
disp('WARNING: CPU/GPU load will spike. Awaiting Episode Manager UI...');

trainingStats = train(agent, env, trainOpts);

disp('Training session terminated. Review the final policy.');