
disp('Initializing Training Protocol...');

trainOpts = rlTrainingOptions(...
    'MaxEpisodes', 10000, ...               
    'MaxStepsPerEpisode', 500, ...         
    'ScoreAveragingWindowLength', 50, ...
    'StopTrainingCriteria', 'AverageReward', ...
    'StopTrainingValue', 800, ...          
    'SaveAgentCriteria', 'EpisodeCount', ... 
    'SaveAgentValue', 500, ...              
    'SaveAgentDirectory', pwd);          

disp('Unleashing SAC Agent into the Environment...');
disp('WARNING: CPU/GPU load will spike. Awaiting Episode Manager UI...');

trainingStats = train(agent, env, trainOpts);

disp('Training session terminated. Review the final policy.');