poolobj = gcp('nocreate');
if isempty(poolobj)
    parpool('local');
end

trainOpts = rlTrainingOptions(...
    'MaxEpisodes', 10000, ...               
    'MaxStepsPerEpisode', 500, ...         
    'ScoreAveragingWindowLength', 50, ...
    'StopTrainingCriteria', 'AverageReward', ...
    'StopTrainingValue', 800, ...          
    'SaveAgentCriteria', 'EpisodeReward', ...  
    'SaveAgentValue', 300, ...                 
    'SaveAgentDirectory', pwd, ...
    'UseParallel', true);                 

trainOpts.ParallelizationOptions.Mode = 'async';

trainingStats = train(agent, env, trainOpts);